title: Hacker-Blog
description: "Grace Leverett's personal blog about tech, life, and everything in between."
author:
  name: "Grace"
  email: "gvleverett@gmail.com"
  url: "https://gracel0721.github.io"
baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Grace Leverett"
year : "2025"
